apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jlcj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jlcj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jlcj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jlcj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jlcj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-stpb-tenant/rhtap-demo-app/hacbs-test-project-jlcj@sha256:c59447ca28472913aa9822b1c465348ea5ef39642a44dab1088d9242333e2550
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
