apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jlcj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-stpb-tenant/rhtap-demo-app/hacbs-test-project-jlcj@sha256:c59447ca28472913aa9822b1c465348ea5ef39642a44dab1088d9242333e2550
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
